---


- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "python-psycopg2"
    - "python-pycurl"

  tags:
    - apt
    - dependencies

- name: Install Postgresql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
  tags:
    - apt
    - dependencies

- name: Stop Postgresql
  service:
    name: postgresql
    state: "stopped"
  tags:
    - service
    - deactivate
    - postgresql
