---



# Gather facts to use the delegation afterwards
- hosts: lbservers
  tasks: []

# Deploy stuff
- name: Ship it!
  hosts: webservers
  sudo: True
  serial: 1

  # Deploy pre tasks
  pre_tasks:
  - name: Disable the favorshare app in haproxy
    shell: echo "disable server favorshare/{{ inventory_hostname }}" | socat stdio "{{ hostvars[item]['haproxy_admin_socket'] }}"
    delegate_to: "{{ item }}"
    with_items: groups.lbservers
    tags:
      - lb
      - disable
      - deployment

  # Deploy roles
  roles:
    - deployment

  post_tasks:
  - name: Wait for webserver to come up
    wait_for: host={{ hostvars[inventory_hostname]['ansible_ssh_host'] }} port={{ nginx_listen_port }} state=started timeout=80
    tags:
      - webserver
      - wait
      - deployment


  - name: Enable the server in haproxy
    shell: echo "enable server favorshare/{{ inventory_hostname }}" | socat stdio "{{ hostvars[item]['haproxy_admin_socket'] }}"
    delegate_to: "{{ item }}"
    with_items: groups.lbservers
    tags:
      - lb
      - enable
      - deployment

  tags:
    - shipit
    - deployment
