---


- name: Common authorization for all servers
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - authorization
  tags:
    - all
    - authorization


- name: Common stuff for all the server
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - common
  tags:
    - all
    - common

