---


- name: Common authorization for all servers
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - authorization
  tags:
    - all
    - authorization


- name: Common stuff for all the server
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - common
  tags:
    - all
    - common

- name: supervisord
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - supervisord
  tags:
    - supervisord
    - install
    - conf

- name: Install postgresql
  hosts: dbservers
  sudo: True
  roles:
    - Ansibles.postgresql
  tags:
    - install
    - postgresql

- name: Post install postgresql
  hosts: dbservers
  sudo: True
  gather_facts: False
  roles:
    - postgresql-postinstall
  tags:
    - postinstall
    - configuration
    - postgresql

- name: Install uwsgi
  hosts: webservers
  sudo: True
  roles:
    - gdamjan.uwsgi
  tags:
    - install
    - uwsgi

#- name: Post install uwsgi
#  hosts: webservers
#  sudo: True
#  gather_facts: False
#  roles:
#    - uwsgi-postinstall
#  tags:
#    - postinstall
#    - configuration
#    - uwsgi
