---

- name: Start nginx
  service:
    name: "supervisord"
    state: "restarted"
  tags:
    - supervisord

- name: Restart nginx
  supervisorctl:
    name: 'nginx'
    state: "restarted"
  tags:
    - supervisor
    - restart
    - nginx
