---


# We could do this per individual
- name: Update apps
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.location }}"
    version: "{{ item.value.version }}"
    accept_hostkey: True
  with_dict: deployment_apps
  tags:
    - apps
    - deploy
    - update

- name: Check apps owner
  file:
    path: "{{ item.value.location }}"
    owner: "{{ service_runner_user }}"
    group: "{{ service_runner_group }}"
    recurse: true
  with_dict: deployment_apps
  tags:
    - apps
    - deploy
    - check
    - owner
    - permissions

- name: Set apps uwsgi files
  template:
    src: uwsgi.ini.j2
    dest: "{{ item.value.app_dir }}/{{ item.key }}/uwsgi.ini"
    owner: "{{ service_runner_user }}"
    group: "{{ service_runner_group }}"
    mode: 0422
  with_dict: deployment_apps
  tags:
    - apps
    - uwsgi

- name: Set apps project settings
  template:
    src: settings.py.j2
    dest: "{{ deployment_apps[item.key]['app_dir'] }}/{{ item.value.settings_path}}"
    owner: "{{ service_runner_user }}"
    group: "{{ service_runner_group }}"
    mode: 0644
  with_dict: django_settings
  tags:
    - apps
    - settings