---


- name: Set motd
  template:
    src: 60-warning.j2
    dest: /etc/update-motd.d/60-warning
    owner: root
    group: root
    mode: 0755
  tags:
    - motd

- name: Set hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags:
    - hostname

- name: Set hostname to hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ machine_hostname }}"
    owner: root
    group: root
    mode: 0644
  notify: Save the hostname
  tags:
    - hostname

- name: Update package repositories
  apt:
    update_cache: True
  tags:
    - apt
    - update_cache

- name: Install common dependencies
  apt:
    name: "{{ item.name }}={{ item.version }}"
    state: present
  with_items: common_dependencies
  tags:
    - apt
    - dependencies